#pragma once
#include <windows.h>

struct PACKET_ID
{
	enum Enum : UINT16
	{
		//SYSTEM
		SYS_USER_CONNECT = 11,
		SYS_USER_DISCONNECT = 12,
		SYS_USER_CONNECT_RESPONSE = 13,
		SYS_END = 30,

		//DB
		DB_END = 199,

		//Client
		LOGIN_REQUEST = 201,
		LOGIN_RESPONSE = 202,

		ROOM_ENTER_REQUEST = 206,
		ROOM_ENTER_RESPONSE = 207,

		ROOM_LEAVE_REQUEST = 215,
		ROOM_LEAVE_RESPONSE = 216,

		ROOM_CHAT_REQUEST = 221,
		ROOM_CHAT_RESPONSE = 222,
		ROOM_CHAT_NOTIFY = 223,

		// UDP
		CHARACTER_SYNC = 1001,
	};
};